# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 926c7c1264b3c553040aa9411c3229c1d7d8cf0b98c318a95cee0a4e61b0726bd20ff2bc1868be8941622992d19c9aad3704e1df428eeabf9918bb7491a48aa3

test:
  secret_key_base: dab218e5802e5b4bc55ababd76de351e4e2b45cfe84c718c1598f2ebe7def1c4e5c47d2c8609b4f0b16c30912ffa9b6ec87bae9e9683786cdc5c78e890ee1d8c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
